---
title: "HW 04"
author: "Nandakumar"
format:
  html:
    embed-resources: true
toc: true
---
```{r setup}
#| warning: false
#| error: false
if (!require("pacman")) 
  install.packages("pacman")

pacman::p_load(glue,ggthemes, openintro, 
               dplyr,ggplot,
    ggrepel,
    ggridges,
    patchwork,
    RColorBrewer,
    readxl,
    scales,
    sf,
    tigris,
    tidyverse)

devtools::install_github("tidyverse/dsbox")


```


## 1 - A second chance

I'm choosing the HW01 -- Question #3c as quoted here -- https://github.com/INFO-526-SU25/hw-01-nandusmart/issues/1

Missed geom_smooth & few others with county data, will try to do it differently this time around.

```{r}
#| label: HW 01_QN 3c
#| warning: false
#| error: false

##Plot A
ggplot2::theme_set(ggplot2::theme(base_size = 16))

plotA <- ggplot(county, aes(x = homeownership, y = poverty)) +
  geom_point() +
  ggtitle("Plot A")

plotB <- ggplot(county, aes(x = homeownership, y = poverty)) +
  geom_point() + geom_smooth(se=FALSE) + labs(title="Plot B")

plotC <- ggplot(county, aes(x=homeownership, y=poverty, group=metro)) + geom_point() + geom_smooth(se=FALSE, color="green") + labs(title="Plot C")

plotD <- ggplot(county, aes(x=homeownership, y=poverty, group=metro)) + geom_smooth(se=FALSE) + geom_point() + labs(title="Plot D")

metro_yes <- county |> filter(metro == "yes")
metro_no <- county  |> filter(metro == "no")
plotE <- ggplot(county, aes(x = homeownership, y = poverty)) +
  geom_point(aes(color = metro)) +
  geom_smooth(
    data = county %>% filter(metro == "no"),
    se = FALSE,
    aes(linetype = "no"),
    color = "#5980fb"
  ) +
  
  geom_smooth(
    data = county %>% filter(metro == "yes"),
    method = "loess", se = FALSE,
    aes(linetype = "yes"),
    color = "#5980fb"
  ) +
  
  scale_color_manual(
    values = c("no" = "#f8766e", "yes" = "#01bfc3", "NA" = "#868686"),
    name = "metro"
  ) +
  scale_linetype_manual(
    values = c("no" = "solid", "yes" = "dashed"),
    name = "metro"
  ) +
  
  theme(
    axis.ticks.length = unit(0.25, "cm"),
    axis.ticks = element_line(color = "black"),
    legend.position = "right",
    legend.box = "vertical"
  ) +
  
  guides(
    linetype = guide_legend(order = 1),  
    color = guide_legend(order = 2)       
  ) +
  
  ggtitle("Plot E")

plotF <- ggplot(county, aes(x=homeownership, y=poverty, group=metro, color=metro)) +
  geom_point() + geom_smooth(se=FALSE) + labs(title="Plot F")


plotG <- ggplot(county, aes(x = homeownership, y = poverty)) +
 labs(title="Plot G") + geom_point(data=county, aes(x=homeownership, y=poverty, color=metro)) + geom_smooth(data=county, aes(x=homeownership, y=poverty), se=FALSE) 

plotH <- ggplot(county, aes(x=homeownership, y=poverty, group=metro, color=metro)) +
  geom_point() +  labs(title="Plot H")


combined_plot <- (plotA | plotB) /
                 (plotC | plotD)
combined_plot2 <- (plotE | plotF) /
                 (plotG | plotH)
                



```


```{r}
#| label: HW 01_QN 3c q
#| warning: false
#| error: false
#| echo: false

combined_plot
combined_plot2
```

## 2.  Arizona state of counties

```{r}
#| label: label-me-2
#| 
#| warning: false
#| error: false

options(tigris_use_cache = TRUE)


az_counties <- counties(state = "AZ", year = 2021, progress_bar = FALSE) |>
  mutate(
   
    name = sub("\\s+County$", "", NAME),
    
    centroid = st_centroid(geometry),
    x = st_coordinates(centroid)[, 1],
    y = st_coordinates(centroid)[, 2]
  ) |>
  select(-centroid) 

```
```{r}
#| label: label-me-2a
#| warning: false
#| error: false


ggplot(az_counties) +
geom_sf(fill = 'grey90', 
        color = "grey10") +

geom_label_repel(aes(x = x, 
                     y = y, 
                     label = NAME),
                 size = 3,
                 min.segment.length = 0.1,
                 box.padding = 0.5,
                 segment.color = "grey20") +

coord_sf() +
labs(
    title = "Counties in Arizona State",
    caption = "Source: Shapefile obtained using {tigris} R package, v2.0.1",
    x = "Longitude",
    y = "Latitude"
) +
  theme_minimal(base_size = 12) + 
  theme(
    panel.background = element_rect(fill = "white", color = NA),
    plot.background = element_rect(fill = "white", color = NA),
    panel.grid = element_line(color = "gray90")
  )
  
```


## 3.  Arizona state of population change

```{r}
#| label: label-me-3
#| warning: false
#| error: false
options(tigris_use_cache = TRUE)
az_counties <- counties(
    state = "AZ",
    year = 2021,
    progress_bar = FALSE
)

pop_data <- read_excel("data/co-est2023-pop-04.xlsx", 
                       skip = 5, 
                       n_max = 15,
                       col_names = c("county", "base_2020", "pop_2020", 
                                     "pop_2021", "pop_2022", "pop_2023"))

pop_data <- pop_data |>
    mutate(
        county = sub("\\.(.+) County, Arizona", "\\1", county),
        total_pop_change_20_23 = pop_2023 - pop_2020
    ) |>
    select(-c(base_2020, pop_2020, pop_2021, pop_2022, pop_2023))

az_data <- az_counties |>
    left_join(
        pop_data, 
        by = c("NAME" = "county")
    )

rdbu_palette <- rev(brewer.pal(5, "RdBu"))

ggplot(data = az_data) +
geom_sf(aes(fill = total_pop_change_20_23), 
        color = "white") +

scale_fill_gradientn(colors = rdbu_palette,
                    name = "Population change",
                    labels = function(x) format(x, big.mark = ",")) +

coord_sf() +
labs(
    title = "Resident Population Change for Counties in AZ",
    subtitle = "July 01, 2020 to July 01, 2023",
    caption = "Source: Shapefile obtained using {tigris} R package, v2.0.1\npopulation change data from the US Census Bureau",
    x = "Longitude",
    y = "Latitude"
) +
  theme_minimal(base_size = 12) + 
  theme(
    panel.background = element_rect(fill = "white", color = NA),
    plot.background = element_rect(fill = "white", color = NA),
    panel.grid = element_line(color = "gray90"),
     plot.title.position = "plot"
  )

```

###Now lets do this plot for total population change from 2021 to 2022 

```{r}
#| label: label-me-3a
#| warning: false
#| error: false

pop_data_new <- read_excel("data/co-est2023-pop-04.xlsx", 
                       skip = 5, 
                       n_max = 15,
                       col_names = c("county", "base_2020", "pop_2020", 
                                     "pop_2021", "pop_2022", "pop_2023"))
pop_data_2122 <- pop_data_new |>
    mutate(
        county = sub("\\.(.+) County, Arizona", "\\1", county),
        total_pop_change_21_22 = pop_2022 - pop_2021
    ) |>
    select(-c(pop_2021, pop_2022))
az_data_new <- az_counties |>
    left_join(
        pop_data_2122, 
        by = c("NAME" = "county")
    )

ggplot(data = az_data_new) +
geom_sf(aes(fill = total_pop_change_21_22), 
        color = "white") +

scale_fill_gradientn(colors = rdbu_palette,
                    name = "Population change",
                    labels = function(x) format(x, big.mark = ",")) +

coord_sf() +
labs(
    title = "Resident Population Change for Counties in AZ",
    subtitle = "2021 to 2022",
    caption = "Source: Shapefile obtained using {tigris} R package, v2.0.1\npopulation change data from the US Census Bureau",
    x = "Longitude",
    y = "Latitude"
) +
  theme_minimal(base_size = 12) + 
  theme(
    panel.background = element_rect(fill = "white", color = NA),
    plot.background = element_rect(fill = "white", color = NA),
    panel.grid = element_line(color = "gray90"),
     plot.title.position = "plot"
  )

```


## 4.  Arizona state of Indiginous Tribal Regions

```{r}
#| label: label-me-4
#| warning: false
#| error: false

az_counties <- counties(
    state = "AZ",
    year = 2021,
    progress_bar = FALSE
)

tribal_data <- st_read("data/American_Indian_Reservations_in_Arizona.shp") |>
    st_transform(crs = st_crs("EPSG:4269")) |>
    mutate(
        x = st_coordinates(st_centroid(geometry))[, 1],
        y = st_coordinates(st_centroid(geometry))[, 2]
    ) |>
    glimpse()

```
 
```{r}
#| label: label-me-4a
#| warning: false
#| error: false

ggplot(az_counties) +
geom_sf(
    fill = 'grey90', 
    color = "white"
) +

geom_sf(
    data = tribal_data, 
    linewidth = 1, 
    fill = NA, 
    color = "black"
) +

geom_label_repel(
    data = tribal_data |>     
        filter(NAME %in% c("Hopi Tribe", 
                           "Navajo Nation", 
                           "White Mountain Apache Tribe", 
                           "San Carlos Apache Tribe", 
                           "Tohono O’odham Nation")),
    aes(x = x, 
        y = y, 
        label = NAME),
    size = 4,
    min.segment.length = 0.1,
    box.padding = 0.5,
    segment.color = "grey20"
) +

coord_sf() +
labs(
    title = "Indigenous Tribal Boundaries in AZ",
    caption = "Source: Shapefile obtained using {tigris} R package, v2.0.1\nIndigenous Tribe Shapefile obtained from AZGeo Data",
    x = "Longitude",
    y = "Latitude"
) +

  theme_minimal(base_size = 12) + 
  theme(
    panel.background = element_rect(fill = "white", color = NA),
    plot.background = element_rect(fill = "white", color = NA),
    panel.grid = element_line(color = "gray90"),
     plot.title.position = "plot"
  )

```

## 5. Arizona state of patchwork

```{r}
#| label: label-me-5
#| warning: false
#| error: false

az_counties <- counties(state = "AZ",
                        year = 2021,
                        progress_bar = FALSE) |>
    mutate(
        name = gsub("\\s+County$", "", NAME),
        x = st_coordinates(st_centroid(geometry))[, 1],
        y = st_coordinates(st_centroid(geometry))[, 2]
    )

tribal_data <- st_read("data/American_Indian_Reservations_in_Arizona.shp") |>
    st_transform(crs = st_crs("EPSG:4269")) |>
    mutate(
        x = st_coordinates(st_centroid(geometry))[, 1],
        y = st_coordinates(st_centroid(geometry))[, 2]
    )

```


```{r}
#| label: label-me-5a
#| warning: false
#| error: false

main_plot <- ggplot(data = az_data) +

    geom_sf(
        aes(fill = total_pop_change_20_23), 
        color = "white"
    ) +
    
    scale_fill_gradientn(
        colors = rdbu_palette,
        name = "Population change",
        labels = function(x) format(x, big.mark = ","),
        guide = guide_colorbar(barwidth = 9,
                               barheight = 1,
                               direction = "horizontal",
                               title.position = "top")
    ) +

    geom_rect(
        aes(xmin = -113.5, 
            xmax = -110, 
            ymin = 31.25, 
            ymax = 34.25),
        fill = NA, 
        color = "black", 
        linetype = "dashed", 
        linewidth = 0.5
    ) +

    geom_segment(
        data = data.frame(x = c(-113.5, -110),
                          y = c(34.25, 31.25),
                          xend = c(-122, -116.75),
                          yend = c(32.75, 28)),
        aes(x = x, 
            y = y, 
            xend = xend, 
            yend = yend),
        color = "black", 
        linetype = "dashed", 
        linewidth = 0.5
    ) +

    geom_label_repel(
        data = filter(az_counties, name %in% c("Maricopa", "Pinal", "Pima")),
        aes(x = x, 
            y = y, 
            label = NAME),
        size = 4,
        min.segment.length = 0.1,
        box.padding = 0.5,
        segment.color = "grey20"
    ) +

    coord_sf(
        xlim = c(-122, -109), 
        ylim = c(28.5, 37)
    ) +

    labs(
        title = "Resident Population Change for Counties in AZ",
        subtitle = "July 01, 2020 to July 01, 2023",
        caption = "Source: Shapefile obtained using {tigris} R package, v2.0.1\npopulation change data from the US Census Bureau\nIndigenous Tribe Shapefile obtained from AZGeo Data",
        x = "Longitude",
        y = "Latitude"
    ) +
    
    theme(
        legend.position = c(0.0, 0.7),
        legend.justification = c(0, 0),
        plot.title.position = "plot",
        panel.background = element_rect(fill = "white", color = NA),
    plot.background = element_rect(fill = "white", color = NA),
    panel.grid = element_line(color = "gray90")
    )




```

```{r}
#| label: label-me-5b
#| warning: false
#| error: false

zoom_plot <- ggplot() +
    geom_sf(
        data = filter(az_data, 
                      NAME %in% c("Maricopa", 
                                  "Pinal", 
                                  "Pima", 
                                  "Santa Cruz", 
                                  "Gila", 
                                  "Yavapai")), 
        aes(fill = total_pop_change_20_23), 
        color = "white"
    ) +

    geom_sf(
        data = tribal_data, 
        fill = NA, 
        color = "black", 
        linewidth = 0.75
    ) +
    
    scale_fill_gradientn(
        colors = rdbu_palette,
        name = NULL,
        labels = NULL,
        limits = range(az_data$total_pop_change_20_23,
                       na.rm = TRUE)
    ) +
    
    geom_label_repel(
        data = filter(tribal_data, 
                      NAME %in% c("White Mountain Apache Tribe",
                                  "San Carlos Apache Tribe",
                                  "Tohono O’odham Nation")),
        aes(x = x, 
            y = y, 
            label = NAME),
        size = 3, 
        box.padding = 0.5, 
        min.segment.length = 0
    ) +

    coord_sf(
        xlim = c(-113.5, -110), 
        ylim = c(31.25, 34.25)
    ) +

    theme_void() +
    theme(
        panel.background = element_rect(fill = "grey50"),
        legend.position = "none"
    )

final_map <- main_plot +
    inset_element(
        zoom_plot, 
        left = 0.0, 
        bottom = 0.0, 
        right = 0.5, 
        top = 0.5
    )

final_map
```